using System.Collections.ObjectModel;
using System.Diagnostics.CodeAnalysis;
using System.Windows.Media;
using Xceed.Wpf.Toolkit;

namespace Wpf_Template
{
    [SuppressMessage("ReSharper", "PossibleNullReferenceException")]
    public class ColorCollections
    {
        private static ColorCollections _instance;
        public static ColorCollections ColorCollection => _instance ?? (_instance = new ColorCollections());
        public ObservableCollection<ColorItem> MaterialColorsCollection { get; private set; } = InitMaterialColorsCollection();
        public ObservableCollection<Color> ColorsCollection { get; private set; } = InitColorsCollection();

        private static ObservableCollection<ColorItem> InitMaterialColorsCollection()
        {
            return new ObservableCollection<ColorItem>
            {
                new ColorItem((Color)ColorConverter.ConvertFromString("#ffebee"), "Red 50"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ffcdd2"), "Red 100"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ef9a9a"), "Red 200"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#e57373"), "Red 300"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ef5350"), "Red 400"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#f44336"), "Red 500"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#e53935"), "Red 600"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#d32f2f"), "Red 700"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#c62828"), "Red 800"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#b71c1c"), "Red 900"),
                //new ColorItem((Color)ColorConverter.ConvertFromString("#ff8a80"), "Red A100"),
                //new ColorItem((Color)ColorConverter.ConvertFromString("#ff5252"), "Red A200"),
                //new ColorItem((Color)ColorConverter.ConvertFromString("#ff1744"), "Red A400"),
                //new ColorItem((Color)ColorConverter.ConvertFromString("#d50000"), "Red A700"),

                new ColorItem((Color)ColorConverter.ConvertFromString("#fce4ec"), "Pink 50"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#f8bbd0"), "Pink 100"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#f48fb1"), "Pink 200"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#f06292"), "Pink 300"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ec407a"), "Pink 400"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#e91e63"), "Pink 500"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#d81b60"), "Pink 600"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#c2185b"), "Pink 700"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ad1457"), "Pink 800"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ad1457"), "Pink 900"),
                //new ColorItem((Color)ColorConverter.ConvertFromString("#ff80ab"), "Pink A100"),
                //new ColorItem((Color)ColorConverter.ConvertFromString("#ff4081"), "Pink A200"),
                //new ColorItem((Color)ColorConverter.ConvertFromString("#f50057"), "Pink A400"),
                //new ColorItem((Color)ColorConverter.ConvertFromString("#c51162"), "Pink A700"),

                new ColorItem((Color)ColorConverter.ConvertFromString("#f3e5f5"), "Purple 50"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#e1bee7"), "Purple 100"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ce93d8"), "Purple 200"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ba68c8"), "Purple 300"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ab47bc"), "Purple 400"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#9c27b0"), "Purple 500"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#8e24aa"), "Purple 600"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#7b1fa2"), "Purple 700"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#6a1b9a"), "Purple 800"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#4a148c"), "Purple 900"),
                //new ColorItem((Color)ColorConverter.ConvertFromString("#ea80fc"), "Purple A100"),
                //new ColorItem((Color)ColorConverter.ConvertFromString("#e040fb"), "Purple A200"),
                //new ColorItem((Color)ColorConverter.ConvertFromString("#d500f9"), "Purple A400"),
                //new ColorItem((Color)ColorConverter.ConvertFromString("#aa00ff"), "Purple A700"),

                new ColorItem((Color)ColorConverter.ConvertFromString("#ede7f6"), "Deep Purple 50"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#d1c4e9"), "Deep Purple 100"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#b39ddb"), "Deep Purple 200"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#9575cd"), "Deep Purple 300"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#7e57c2"), "Deep Purple 400"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#673ab7"), "Deep Purple 500"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#5e35b1"), "Deep Purple 600"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#512da8"), "Deep Purple 700"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#4527a0"), "Deep Purple 800"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#311b92"), "Deep Purple 900"),

                new ColorItem((Color)ColorConverter.ConvertFromString("#e8eaf6"), "Indigo 50"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#c5cae9"), "Indigo 100"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#9fa8da"), "Indigo 200"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#7986cb"), "Indigo 300"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#5c6bc0"), "Indigo 400"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#3f51b5"), "Indigo 500"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#3949ab"), "Indigo 600"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#303f9f"), "Indigo 700"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#283593"), "Indigo 800"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#1a237e"), "Indigo 900"),

                new ColorItem((Color)ColorConverter.ConvertFromString("#e3f2fd"), "Blue 50"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#bbdefb"), "Blue 100"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#90caf9"), "Blue 200"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#64b5f6"), "Blue 300"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#42a5f5"), "Blue 400"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#2196f3"), "Blue 500"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#1e88e5"), "Blue 600"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#1976d2"), "Blue 700"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#1565c0"), "Blue 800"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#0d47a1"), "Blue 900"),

                new ColorItem((Color)ColorConverter.ConvertFromString("#e1f5fe"), "Light Blue 50"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#b3e5fc"), "Light Blue 100"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#81d4fa"), "Light Blue 200"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#4fc3f7"), "Light Blue 300"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#29b6f6"), "Light Blue 400"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#03a9f4"), "Light Blue 500"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#039be5"), "Light Blue 600"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#0288d1"), "Light Blue 700"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#0277bd"), "Light Blue 800"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#01579b"), "Light Blue 900"),

                new ColorItem((Color)ColorConverter.ConvertFromString("#e0f7fa"), "Cyan 50"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#b2ebf2"), "Cyan 100"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#80deea"), "Cyan 200"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#4dd0e1"), "Cyan 300"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#26c6da"), "Cyan 400"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#00bcd4"), "Cyan 500"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#00acc1"), "Cyan 600"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#0097a7"), "Cyan 700"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#00838f"), "Cyan 800"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#006064"), "Cyan 900"),

                new ColorItem((Color)ColorConverter.ConvertFromString("#e0f2f1"), "Teal 50"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#b2dfdb"), "Teal 100"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#80cbc4"), "Teal 200"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#4db6ac"), "Teal 300"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#26a69a"), "Teal 400"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#009688"), "Teal 500"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#00897b"), "Teal 600"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#00796b"), "Teal 700"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#00695c"), "Teal 800"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#004d40"), "Teal 900"),

                new ColorItem((Color)ColorConverter.ConvertFromString("#e8f5e9"), "Green 50"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#c8e6c9"), "Green 100"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#a5d6a7"), "Green 200"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#81c784"), "Green 300"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#66bb6a"), "Green 400"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#4caf50"), "Green 500"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#43a047"), "Green 600"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#388e3c"), "Green 700"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#2e7d32"), "Green 800"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#1b5e20"), "Green 900"),

                new ColorItem((Color)ColorConverter.ConvertFromString("#f1f8e9"), "Light Green 50"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#dcedc8"), "Light Green 100"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#c5e1a5"), "Light Green 200"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#aed581"), "Light Green 300"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#9ccc65"), "Light Green 400"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#8bc34a"), "Light Green 500"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#7cb342"), "Light Green 600"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#689f38"), "Light Green 700"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#558b2f"), "Light Green 800"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#33691e"), "Light Green 900"),

                new ColorItem((Color)ColorConverter.ConvertFromString("#f9fbe7"), "Lime 50"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#f0f4c3"), "Lime 100"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#e6ee9c"), "Lime 200"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#dce775"), "Lime 300"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#d4e157"), "Lime 400"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#cddc39"), "Lime 500"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#c0ca33"), "Lime 600"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#afb42b"), "Lime 700"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#9e9d24"), "Lime 800"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#827717"), "Lime 900"),

                new ColorItem((Color)ColorConverter.ConvertFromString("#fffde7"), "Yellow 50"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#fff9c4"), "Yellow 100"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#fff59d"), "Yellow 200"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#fff176"), "Yellow 300"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ffee58"), "Yellow 400"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ffeb3b"), "Yellow 500"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#fdd835"), "Yellow 600"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#fbc02d"), "Yellow 700"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#f9a825"), "Yellow 800"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#f57f17"), "Yellow 900"),

                new ColorItem((Color)ColorConverter.ConvertFromString("#fff8e1"), "Amber 50"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ffecb3"), "Amber 100"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ffe082"), "Amber 200"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ffd54f"), "Amber 300"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ffca28"), "Amber 400"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ffc107"), "Amber 500"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ffb300"), "Amber 600"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ffa000"), "Amber 700"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ff8f00"), "Amber 800"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ff6f00"), "Amber 900"),

                new ColorItem((Color)ColorConverter.ConvertFromString("#fff3e0"), "Orange 50"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ffe0b2"), "Orange 100"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ffcc80"), "Orange 200"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ffb74d"), "Orange 300"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ffa726"), "Orange 400"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ff9800"), "Orange 500"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#fb8c00"), "Orange 600"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#f57c00"), "Orange 700"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ef6c00"), "Orange 800"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#e65100"), "Orange 900"),

                new ColorItem((Color)ColorConverter.ConvertFromString("#fbe9e7"), "Deep Orange 50"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ffccbc"), "Deep Orange 100"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ffab91"), "Deep Orange 200"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ff8a65"), "Deep Orange 300"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ff7043"), "Deep Orange 400"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ff5722"), "Deep Orange 500"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#f4511e"), "Deep Orange 600"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#e64a19"), "Deep Orange 700"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#d84315"), "Deep Orange 800"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#bf360c"), "Deep Orange 900"),

                new ColorItem((Color)ColorConverter.ConvertFromString("#efebe9"), "Brown 50"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#d7ccc8"), "Brown 100"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#bcaaa4"), "Brown 200"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#a1887f"), "Brown 300"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#8d6e63"), "Brown 400"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#795548"), "Brown 500"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#6d4c41"), "Brown 600"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#5d4037"), "Brown 700"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#4e342e"), "Brown 800"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#3e2723"), "Brown 900"),

                new ColorItem((Color)ColorConverter.ConvertFromString("#fafafa"), "Grey 50"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#f5f5f5"), "Grey 100"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#eeeeee"), "Grey 200"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#e0e0e0"), "Grey 300"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#bdbdbd"), "Grey 400"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#9e9e9e"), "Grey 500"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#757575"), "Grey 600"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#616161"), "Grey 700"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#424242"), "Grey 800"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#212121"), "Grey 900"),

                new ColorItem((Color)ColorConverter.ConvertFromString("#eceff1"), "Blue Grey 50"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#cfd8dc"), "Blue Grey 100"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#b0bec5"), "Blue Grey 200"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#90a4ae"), "Blue Grey 300"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#78909c"), "Blue Grey 400"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#607d8b"), "Blue Grey 500"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#546e7a"), "Blue Grey 600"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#455a64"), "Blue Grey 700"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#37474f"), "Blue Grey 800"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#263238"), "Blue Grey 900"),

                new ColorItem((Color)ColorConverter.ConvertFromString("#000000"), "Black"),
                new ColorItem((Color)ColorConverter.ConvertFromString("#ffffff"), "White"),
            };
        }
        private static ObservableCollection<Color> InitColorsCollection()
        {
            return new ObservableCollection<Color>
        {
            (Color) ColorConverter.ConvertFromString("#e91e63"),
            (Color) ColorConverter.ConvertFromString("#3f51b5"),
            (Color) ColorConverter.ConvertFromString("#8bc34a"),
            (Color) ColorConverter.ConvertFromString("#ffc107"),
            (Color) ColorConverter.ConvertFromString("#f44336"),
            (Color) ColorConverter.ConvertFromString("#673ab7"),
            (Color) ColorConverter.ConvertFromString("#03a9f4"),
            (Color) ColorConverter.ConvertFromString("#4caf50"),
            (Color) ColorConverter.ConvertFromString("#ffeb3b"),
            (Color) ColorConverter.ConvertFromString("#ff5722"),
            (Color) ColorConverter.ConvertFromString("#9c27b0"),
            (Color) ColorConverter.ConvertFromString("#2196f3"),
            (Color) ColorConverter.ConvertFromString("#ff9800"),
            (Color) ColorConverter.ConvertFromString("#607d8b"),
            (Color) ColorConverter.ConvertFromString("#795548")
        };
        }
    }
}
